# Generated by Django 5.1.7 on 2025-03-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='category',
            new_name='category_set',
        ),
    ]
