# Generated by Django 5.1.7 on 2025-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_category_quiz_category_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='language',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subtitle_kz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_kz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='categoryset',
            name='categories',
            field=models.ManyToManyField(related_name='category_sets', to='quiz.category'),
        ),
    ]
