# Generated by Django 5.1.7 on 2025-03-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_language_remove_quiz_subtitle_kz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category'),
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
