# Generated by Django 5.1.7 on 2025-03-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizresult_quiz_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text_kz',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text_ru',
        ),
    ]
