# Generated by Django 5.1.7 on 2025-04-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_quiz_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('category_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoryset')),
            ],
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
