# Generated by Django 5.1.7 on 2025-04-01 11:03

import django.db.models.deletion
import quiz.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_quizresult_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.quiz_result_pdf_path),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='unanswered_questions',
            field=models.ManyToManyField(blank=True, related_name='unanswered_by', to='quiz.question'),
        ),
    ]
