# Generated by Django 5.1.7 on 2025-04-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_quizresult_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz'),
        ),
    ]
