# Generated by Django 5.1.7 on 2025-04-02 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizresult_name_quizresult_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoryset'),
        ),
    ]
