# Generated by Django 5.1.7 on 2025-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quiz_category_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
