# Generated by Django 5.1.7 on 2025-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_answer_text_kz_answer_text_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='diagnostic_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quiz_diagnostics/'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='result_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results/'),
        ),
    ]
