# Generated by Django 5.1.7 on 2025-04-03 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_answer_image_alter_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryset',
            options={'verbose_name': 'Category Set', 'verbose_name_plural': 'Category Sets'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'Quiz Result', 'verbose_name_plural': 'Quiz Results'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('EXC', 'Exact'), ('NTR', 'Natural')], max_length=8, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='categoryset',
            name='categories',
            field=models.ManyToManyField(related_name='category_sets', to='quiz.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='categoryset',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Category Set Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subcategory', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoryset', verbose_name='Category Set'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user_token',
            field=models.CharField(max_length=128, verbose_name='User Token'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.answer', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='diagnostic_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quiz_diagnostics/', verbose_name='Diagnostic PDF'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parent Name'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='result_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results/', verbose_name='Result PDF'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='unanswered_questions',
            field=models.ManyToManyField(blank=True, related_name='unanswered_by', to='quiz.question', verbose_name='Unanswered Questions'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='User Token'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_kz',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
    ]
