# Generated by Django 5.1.7 on 2025-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parent Name'),
        ),
    ]
