# Generated by Django 5.1.7 on 2025-04-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_quiz_name_quiz_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='phone_number',
        ),
    ]
