# Generated by Django 5.1.7 on 2025-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_quizresult_name_remove_quizresult_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 correct answer'), (2, '2 correct answers'), (3, '3 correct answers')], default=1, verbose_name='Correct Answers Count'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_possible_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Possible Points'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_points',
            field=models.PositiveIntegerField(default=0, verbose_name='User Points'),
        ),
    ]
