# Generated by Django 5.1.7 on 2025-04-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_question_correct_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='answer',
            name='image_kz',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers/kz', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers/ru', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_kz',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions/kz', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions/ru', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
    ]
