# Generated by Django 5.1.7 on 2025-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_answer_image_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image_kz',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers/kz', verbose_name='Image kz'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers/ru', verbose_name='Image ru'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_kz',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions/kz', verbose_name='Image kz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions/ru', verbose_name='Image ru'),
        ),
    ]
