# Generated by Django 5.2.3 on 2025-06-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_answer_image_kz_alter_answer_image_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subject_type',
            field=models.CharField(choices=[('MAIN', 'Основной'), ('PROFILE', 'Профильный')], default='', verbose_name='Subject_type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mark', models.IntegerField(verbose_name='Mark')),
                ('categories', models.ManyToManyField(related_name='category_specialization_sets', to='quiz.category', verbose_name='Categories')),
            ],
        ),
    ]
