# Generated by Django 5.2.3 on 2025-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_category_subject_type_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='categories',
            field=models.ManyToManyField(related_name='category_specialization_sets', to='quiz.categoryset', verbose_name='Categories'),
        ),
    ]
