# Generated by Django 5.1.7 on 2025-03-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_answer_text_kz_remove_answer_text_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='category',
        ),
    ]
